### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by s4m-mo** [Neuron-AI/neuron-ai.github.io#5]
@Harry-Hopkinson since [here](https://github.com/Neuron-AI/neuron-ai.github.io/commit/eedb46e70440f5295aecb6b061f41fca1680b0bf), there was  suddenly an issue and  the page wouldn't load and went all weird. Also, can you make one larger commit with a PR rather than lots of tiny ones.

**Comment by Harry-Hopkinson** [comment]
Okay sorry

**Comment by Harry-Hopkinson** [comment]
My website works fine on my end - opened it on localhost and everything is working smoothly - did you commit anything?

**Comment by Harry-Hopkinson** [comment]
Issue Fixed...

**Comment by s4m-mo** [comment]
sorry, it was between 2 of your commits. Have you branched it?

**Comment by s4m-mo** [comment]
@Harry-Hopkinson 
Can you still see the organization discussions?
