### ISSUE TITLE
Responsiveness of the website 

### ISSUE THREAD

**Issue by amhsirak** [Neuron-AI/neuron-ai.github.io#7]
### Dimension: 280 x 653

<img width="800" alt="galaxy" src="https://user-images.githubusercontent.com/76456498/141106637-dc352e7c-d2ae-4580-8203-f5aa4f2f8d92.png">

### Dimension: 360 x 640

<img width="800" alt="galaxy" src="https://user-images.githubusercontent.com/76456498/141106667-d2478de5-b9e7-4a1d-a845-808d60e0fc5b.jpg">

**Comment by s4m-mo** [comment]
I will read this through properly and reply in around half an hour.

**Comment by s4m-mo** [comment]
Just got back! Hi 👋! I am looking into this and fixing it right now. I'll link the pull request and fix it within the hour.

**Comment by s4m-mo** [comment]
@karishmashuklaa @Harry-Hopkinson 
I have recently pushed to a  branch called `improve-styles-responsiveness`,  and it won't render on my side. Can someone check this?

**Comment by s4m-mo** [comment]
@karishmashuklaa if you are up for completing this, please do!

**Comment by amhsirak** [comment]
@Password-Classified Yes sure! I will start working on it and make a PR ASAP

**Comment by s4m-mo** [comment]
Thanks!

**Comment by s4m-mo** [comment]
This is GREAT!!!!!!!! Thanks so much.

Is it possible that the 3 links in the nav could be centered (except the `Neuron AI` title)

**Comment by amhsirak** [comment]
@Password-Classified Yes.

**Comment by s4m-mo** [comment]
Thanks so much!

**Comment by s4m-mo** [comment]
Has the center title been done yet?

**Comment by s4m-mo** [comment]
We can probably leave the center title. It actually looks better how it is.
